name: Publish to Maven Central

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: publish
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      # GPG key set up according to https://stackoverflow.com/a/61748039
      - name: Configure GPG
        run: |
          echo ${{ secrets.GPG_SIGNING_KEY }} | base64 --decode | gpg --import
      - name: Publish to Maven
        run: |
          ./mill mill.scalalib.PublishModule/publishAll \
          --sonatypeUri "https://s01.oss.sonatype.org/service/local" \
          --sonatypeSnapshotUri "https://s01.oss.sonatype.org/content/repositories/snapshots" \
          --gpgArgs --passphrase="",--batch,--yes,-a,-b \
          --publishArtifacts __.publishArtifacts \
          --release true \
          --signed true
