name: Publish to Maven Central

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run tests
        run: |
          echo $GPG_PRIVATE_KEY > gpg_key
          gpg --import --no-tty --batch --yes gpg_key
          rm gpg_key
          ./mill mill.scalalib.PublishModule/publishAll \
            --sonatypeUri "https://s01.oss.sonatype.org/service/local" \
            --sonatypeSnapshotUri "https://s01.oss.sonatype.org/content/repositories/snapshots" \
            --gpgArgs --passphrase="",--batch,--yes,-a,-b \
            --publishArtifacts __.publishArtifacts \
            --release true \
            --signed true
