name: Test

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-jvm:
    name: Test (JVM)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run tests
        run: ./mill "sline[_]".jvm.test

  test-native:
    name: Test (Native)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Run tests
        if: matrix.os != 'windows-latest'
        run: ./mill "sline[_]".native.test
      - name: Run tests
        if: matrix.os == 'windows-latest'
        run: .\mill "sline[_]".native.test
